### ISSUE TITLE
should length to delta round?

### ISSUE THREAD

**Issue by willm** [jimm/midilib#12]
The `length_to_delta` method on sequence currently strips any decimal place to return only the integer part. When dealing with data that has been input from live playing (not quantized) this could be problematic.

eg:

```
seq.ppqn = 96
seq.length_to_data(0.237) #22.752 is interpreted as 22.
```

instead of `to_i`, would it not perhaps be better to use `.round`?

**Comment by jimm** [comment]
@willm This is horribly delayed, but thank you for your suggestion. I agree, and have changed `Sequence.length_to_delta` so that it now calls `.round`.

I need to look for open issues more often, obviously!
