### ISSUE TITLE
delta_time needs a descriptive comment

### ISSUE THREAD

**Issue by willhaslett** [jimm/midilib#20]
Hi! I'm enjoying this great gem. I had to do some code reading and trial-and-error to figure out that `delta_time` means 'duration' for an event. `delta_time` is an ambiguous name and the [comment where it is declared](https://github.com/jimm/midilib/blob/d9364b82e313d61f7157c2a103b125b4a3162970/lib/midilib/event.rb#L9) doesn't describe the variable, it only gives a warning. Since the variable is public, I don't imagine that a name change would be wise. Can we add a description to the comment, something like "The duration of the event in MIDI pulses" (I _think_ those are the units?).

I don't think that this is a nitpick because the variable is so important. I'd be happy to submit a patch.

**Comment by willhaslett** [comment]
Never mind. After further reading, imo, there are numerous ambiguities in naming and absent descriptions (backs away).

**Comment by jimm** [comment]
@willhaslett thank you for pointing out that the code comments need improving.

Just so you know, `delta_time` is part of the MIDI file standard. Every event in a MIDI file starts with a delta time, which is its time in ticks after the previous event. For example, if there are two notes in a row in a MIDI file and the delta time of the second one is zero, it gets played at the same time as the first one.
