### ISSUE TITLE
Any plan to release 3.x to rubygems?

### ISSUE THREAD

**Issue by ushiushix** [jimm/midilib#23]
Do you have any plan to release midilib 3.x to rubygems?

Midilib in rubygems is stopped at 2.0.5, which turned out to not compatible to ruby 3. I believed that is the latest development for a long time.
However today I checked out the latest source and the test successfully ran in ruby 3.1.2.
I expect the valuable library to be updated and live with ruby 3 in rubygems. Is there any issue which prevents the release, or any breaking changes?

**Comment by jimm** [comment]
@ushiushix The version number of midilib has nothing to do with the version number of Ruby that it supports. I don't see a need to update midilib's version number. Is there something I'm not understanding?

**Comment by jimm** [comment]
@ushiushix Ah, I understand: I need to update the info at rubygems. I'll do that when I'm able. Thank you for pointing this out.

**Comment by jimm** [comment]
Done: I've just pushed version 3.0.1 to rubygems. Thanks for pointing this out, @ushiushix.

**Comment by jimm** [comment]
In fact, I've just merged a fix by another user in #21 and bumped up the version number to 3.1.0 as well.

**Comment by ushiushix** [comment]
I have confirmed that 3.1.0 and 3.0.1 is available from rubygems.
Thanks for quick reply.

Also thanks for maintaining this useful library.
