### ISSUE TITLE
Feature suggestion: determine track duration in SeqReader#eot for META_TRACK_END events

### ISSUE THREAD

**Issue by mike-bourgeous** [jimm/midilib#24]
Hi there!  I use midilib in a couple of my own projects, so thanks for writing it!

One of my projects is a toy FM synthesizer that can play a MIDI file.  To detect the end of a song, I use the latest of the final note-off event, the final event in any track, or the final oscillator envelope decay.  It'd be nice to be able to use the delta time of the `FF 2F 00` track end meta-event to determine track length instead, at least for looping.

If this sounds interesting, I'd be happy to open a merge request that adds a `track_length` or `duration` attribute to MIDIFile, and modify `SeqReader#eot` to save track length (but while still not adding the META_TRACK_END event to the event list, in keeping with documented behavior).

**Comment by mike-bourgeous** [comment]
Makes sense.  I hope to find time to take a stab at this later this week.

**Comment by jimm** [comment]
If you don't have time or you just don't feel like working on this, let me know. I happen to be between jobs right now and have a bit of time on my hands. Otherwise, I'd welcome your contribution.

If you do work on it, please include tests. And we should probably bump up to the next major version number in `lib/midilib/info.rb` since this will be a breaking change.

**Comment by mike-bourgeous** [comment]
Don't let me stop you from working on your own project!  I have plenty of other ideas if you beat me to this one :)

**Comment by jimm** [comment]
I'm on it, then. Thank you for raising this issue, @mike-bourgeous.

**Comment by jimm** [comment]
I've merged the fix. I want to fix #26 before making an official release, though if that fix takes too long I will release this first.

**Comment by mike-bourgeous** [comment]
I confirmed that the `main` midilib branch shows the right timestamp for the track end event in my code.  Thanks!

![image](https://user-images.githubusercontent.com/5015814/215010257-10e39035-c70b-4933-99d0-99eae51999d7.png)

**Comment by jimm** [comment]
Thank you for confirming the fix!
