### ISSUE TITLE
Notes get moved forward in time

### ISSUE THREAD

**Issue by mohanklein** [jimm/midilib#26]
I am not that much into the whole midi spec sorry about that, but maybe you can help me on this one maybe this is a problem in the midi file and not a problem with midilib:
When I just run the attached original midi file (I don't know how this was exported) through midilib via
`seq.each { | track |  track.each { | event | ... } }`
without even manipulating it at all I get the result shown in the attached screenshot. It works until the marked point, then notes seem to get shifted "forward in time".

Maybe this has something to do with midi export resolution, delta times, I would be happy if anyone could help me understand this.

Thank you so much already!

<img width="955" alt="Bildschirm­foto 2023-01-19 um 18 56 55" src="https://user-images.githubusercontent.com/7778513/213523730-6b6c4327-0d37-4858-8352-5cffedc15a02.png">

[midi-files.zip](https://github.com/jimm/midilib/files/10459655/midi-files.zip)

**Comment by jimm** [comment]
@mohanklein Here's what's happening: the original file has nine different note off messages that are duplicates: there is first a note on message, then a note off message, then another note off message for the same note. midilib isn't handling that properly --- you've found a bug.

I'll fix this bug as soon as I'm able, and will link the PR to this issue.

(By the way, technically the note off messages are note on messages with zero velocity. The MIDI spec says to treat those as note off messages because, in conjunction with running status bytes, that can save space and make MIDI files smaller. I don't think that's important here.)

**Comment by mohanklein** [comment]
awesome jimm! thank you so much! looking forward to your bug fix. love this library!

**Comment by mohanklein** [comment]
@jimm hey jimm! any news on this problem, can I provide further example files to help you fix this as I found more having the same problem? but probably you just did not yet have time to look into it, sorry to bother if so! love from germany!

**Comment by jimm** [comment]
@mohanklein I'm sorry but I haven't had much time to put into it. The MIDI files are definitely odd, with the duplicate note offs for the same not, though not technically illegal at all. I need to make the time to reproduce the problem in test code.

Unfortunately, I've just started a new job so I don't have a lot of time to focus on this right now. I will get to it when I am able, however. Sorry, and thank you for your patience.

**Comment by jimm** [comment]
I believe this is not a bug in how midilib handles multiple note offs for the same note on, but instead a bug in how it handles running status bytes. (Running status bytes exist to save space. If multiple messages in a row use exactly the same status byte, then the status byte can be omitted every time after the first.)

**Comment by jimm** [comment]
OK, I definitely have a fix. I've proven it works by comparing text versions of the output after the fix and your original file. The bug is not in the code that reads MIDI files, it's in the code that writes them. That code attempts to use running status bytes, compressing the output.

Now all I have to do is write a test to cover these changes. There are currently no tests that test the running status byte output code at all.

**Comment by jimm** [comment]
@mohanklein may I add your `orig.mid` file to midilib's test files and use it in the tests? If so, would you like credit and/or a copyright notice and what should that be? (You will automatically get credit in the CREDITS file for finding the bug.)

**Comment by jimm** [comment]
Actually @mohanklein can you please give me more details about how you created `after-midilib.rb`, either the whole Ruby script, or at least the chunk of code that read in the original, did whatever you did, and then wrote it out? There might be something in that code that will help me figure out how you got the results you did.

The thing is, when I run the following test code it passes. The events that are read in from your original file match what gets written out and read back in. I don't get the same thing you see in `after-midilib.rb`.

```
# Regression test. Running status output when writing a track's events was broken.
def test_running_status_output
  orig_seq = MIDI::Sequence.new
  File.open(File.join(ENV['HOME'], 'Downloads/midilib/org.mid'), 'rb') { |file| orig_seq.read(file) }
  File.open(TEMPFILE, 'wb') { |file| orig_seq.write(file) }
  round_trip_seq = MIDI::Sequence.new
  File.open(TEMPFILE, 'rb') { |file| round_trip_seq.read(file) }
  assert_equal(orig_seq.tracks.length, 1)
  orig_seq.tracks[0].events.zip(round_trip_seq.tracks[0].events).each do |orig_event, rts_event|
    assert_equal(orig_event.data_as_bytes, rts_event.data_as_bytes)
    assert_equal(orig_event.delta_time, rts_event.delta_time)
    assert_equal(orig_event.time_from_start, rts_event.time_from_start)
  end
end
```

**Comment by mohanklein** [comment]
@jimm I will ask the creator regarding the `org.mid` for use in your tests. For now I don't see any problem or need for credit with those few notes :-)

**Comment by jimm** [comment]
@mohanklein thanks for the code snippet. I'll play with that in my new test and see what results I get. I didn't realize that's not your MIDI file, so don't worry about it. I'll come up with something else.

**Comment by mohanklein** [comment]
@jimm I asked the vendor as it is an extract from an "Ugritone" midi groove and I made presets and a video for them, I know the guy and messaged him. I don't think he'll have a problem. I'll let you know when he answers.

**Comment by mohanklein** [comment]
@jimm hey man! don't want to stress you, just wanted to ask if there is anything I can do to help you finish a fix for this? anything you need? love from germany!

**Comment by jimm** [comment]
Sorry for the delay, @mohanklein. I'll try to dig in again when I have time and see what is different between your processor.rb script and my test.

**Comment by jimm** [comment]
Also, what version of midilib are you running? You can tell by typing `gem info midilib`

**Comment by mohanklein** [comment]
so this was on midilib (2.0.5) I will now upgrade and see if it still persists

**Comment by mohanklein** [comment]
update :-)

**Comment by mohanklein** [comment]
@jimm now the md5 is different than the problematic file ... still different than the org file which is absolutely normal I guess after touching it somehow :-)
<img width="816" alt="Bildschirmfoto 2023-09-11 um 18 11 34" src="https://github.com/jimm/midilib/assets/7778513/86e5cd84-e722-411e-b229-3c8a9a3b8aa9">

**Comment by jimm** [comment]
Yes, `b2a4...` is the md5 hash that I would expect. Does the note data in the new version look good to you? It passes all of my tests.

**Comment by mohanklein** [comment]
@jimm this seems to have resolved the issue and works great! please see the optical comparison attached. the first track is the original and the last one the new (local) midilib version I downloaded. the notes don't get shifted forward. I also tested a big midi test file and actually manipulated the notes a lot and except a different file hash everything is correct regarding the content/result!!! great man! so can you release this version? one thing I found kind of confusing is your version management? I can't really find releases and it seems version 2.0.5 is the default but there also already is a version 4.0.0 on rubygems? can you help me what's going on here :-) thanks for the great fix!!!

<img width="1404" alt="Bildschirmfoto 2023-09-12 um 13 00 36" src="https://github.com/jimm/midilib/assets/7778513/c79fc916-0d4f-43ea-9b85-770369218193">

**Comment by jimm** [comment]
Glad to hear that updating the code worked for you. As for Rubygems, midilib is on there now, and was at 4.0.0 until a few minutes ago. It's now at 4.0.2. I just ran `gem install midilib` on a machine that didn't have it installed and it worked fine. Depending on how you installed it, if you run `gem update midilib` it should update it. If you are using `bundle` within a project then `bundle update midilib` should work, as long as you aren't specifying in your Gemfile, or it allows installation of version 4.x.
