### ISSUE TITLE
sequence.format is ignored when writing files

### ISSUE THREAD

**Issue by adamjmurray** [jimm/midilib#6]
I wouldn't mind trying to fix this and sending you a pull request. Before I spend time on it, I was wondering if there was a reason you ignore the sequence.format in SeqWriter#write_header:
https://github.com/jimm/midilib/blob/master/lib/midilib/io/seqwriter.rb#L32
?

**Comment by jimm** [comment]
Because midilib only handles one format. I have not planned to add support for other formats.
