### ISSUE TITLE
Docu example: how to play a midi file from within ruby?

### ISSUE THREAD

**Issue by shevegen** [jimm/midilib#7]
Hi,

Could a simple example be added to the intro-documentation so that newcomers like me can figure out how to play midi files from within ruby?

Whether it is possible to do so without having to rely on external players, or whether it is only possible with i.e. mplayer.

Whatever the solution, I think a short section to tell people how to play those created midi files would be AWESOME!

**Comment by jimm** [comment]
Thanks, @hrigu.
